### ISSUE TITLE
Feedback would be nice

### ISSUE THREAD

**Issue by tgetgood** [tgetgood/whodunnit#1]
@RichardLitt I think this is what you're looking for. 

Anything else you can think of that would be useful in this vein?

Maybe a better name is in order.

**Comment by RichardLitt** [comment]
- Can we run this from the CLI without piping from name-your-contribs, but just calling whodunnit?
- Can you include an example in the README?
- Can you publish this and show how to use it with a bin? No reason to have to clone this when I can npm i -g

**Comment by RichardLitt** [comment]
The name is good. :)

**Comment by tgetgood** [comment]
The reason I chose to make this a pipe in script is that I didn't want to replicate (or copy paste) the entire cli interface of name-your-contributors here. I don't know of any way to reuse a cli. Do you have any ideas? We could separate the cli part into its own repo and install it into both. That seems like a real kludge though, and I'm not entirely sure it would work.

We could move it in here, but then any changes we make to nyc will need to be copied over manually unless we find some way to share a cli. 

Points 2 and 3 are good. I'll make them their own issues.

**Comment by RichardLitt** [comment]
Makes sense for me. Lets leave the CLI as it is.
