### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by RichardLitt** [tgetgood/whodunnit#13]
```sh
npm ERR! You do not have permission to publish "whodidwhat". Are you logged in as the correct user? : whodidwhat
```

@tgetgood Any ideas?

**Comment by tgetgood** [comment]
What's your username on npm? I'll add you to the collaborators. Ideally I would transfer ownership of it, do you know how to do that with npm packages?

**Comment by RichardLitt** [comment]
I'm on npm as [richardlitt](https://www.npmjs.com/~richardlitt). `npm owner --help` should give all of the information needed. Thank you!

**Comment by tgetgood** [comment]
You are now an owner. Try it out and let me know if everything's good.

**Comment by RichardLitt** [comment]
It worked! Thanks, @tgetgood.
