### ISSUE TITLE
Are these coordinates accurate?

### ISSUE THREAD

**Issue by RichardLitt** [tgetgood/whodunnit#2]
https://github.com/tgetgood/whodunnit/blob/9743a275b11559340845d86fd6abaaa0810f0949/package.json#L49

If not, remove them.

**Comment by tgetgood** [comment]
Well they're in Montreal. Is that what npm means by coordinates though? I just copied it from name-your-contributors.

**Comment by RichardLitt** [comment]
They were holdovers from a location package that no longer works, sadly. :( I'll just remove them.
