### ISSUE TITLE
Move to mntnr?

### ISSUE THREAD

**Issue by RichardLitt** [tgetgood/whodunnit#4]
Do you want this here? Mind if we move it?

**Comment by tgetgood** [comment]
I just tried and don't have permission. I've invited you as a collaborator. Feel free to move transfer it.

**Comment by RichardLitt** [comment]
Accepted. Need admin, though.

**Comment by tgetgood** [comment]
I don't see how to do that. I've transfered it to you, so you can move it on.

**Comment by RichardLitt** [comment]
Done!
